config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/join', to: 'users#new'
  post '/join', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]

  mount Tus::Server => "/files"
  mount LetterOpenerWeb::Engine, at: 'letter_opener' if Rails.env.development?
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if loggedin?
      @micropost = current_user.microposts.build if loggedin?
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_authed_root.html.erb
<aside class="col-md-4">
  <section class="user_info">
    <%= render 'shared/user_info' %>
  </section>
  <section class="micropost_form">
    <%= render 'shared/micropost_form' %>
  </section>
</aside>

app/views/static_pages/_unauthed_root.html.erb
<div class="center jumbotron">
  <h1>Welcome to the AuthServer</h1>

  <h2>
    This is the home page for the <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    application.
  </h2>

  <%= link_to "Join now!!", join_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a <a href="https://railstutorial.jp/#ebook">book</a> and
  <a href="https://railstutorial.jp/#screenshot">screencast</a>
  to teach web development with
  <a href="http://rubyonrails.org">Ruby on Rails</a>.
  This is the auth server app for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">Rails Tutorial help page</a>
  To get help on this app, see the
  <a href="https://railstutorial.jp/#ebook"><em>Ruby on Rails Tutorial</em>book</a>
</p>

app/views/static_pages/home.html.erb
<% if loggedin? %>
  <div class="row">
    <%= render 'static_pages/authed_root' %>
    <%= render 'shared/feed' %>
  </div>
<% else %>
  <%= render 'static_pages/unauthed_root' %>
<% end %>